name: Publish Superadmin to Cloudflare Pages

on:
  push:
    paths:
      - .github/workflows/publish-superadmin.yaml
      - packages/superadmin/**

env:
  PUBLIC_APEX_DOMAIN: ${{ vars.PUBLIC_APEX_DOMAIN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.9.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Prepare build
        run: |
          pnpm i
          cd packages/superadmin
          pnpm build

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.5.0

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        id: deployment
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pockethost-superadmin
          directory: ./dist/superadmin
          branch: ${{ github.head_ref || github.ref_name }}
          wranglerVersion: '3'

      - name: Discord feature branch notification
        if: github.ref_name != 'v0/main'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '**SUPERADMIN PREVIEW** ${{ steps.deployment.outputs.url }} was generated by ${{ github.actor }} in [${{ env.GIT_COMMIT_SHORT_SHA }}](https://github.com/${{ github.repository}}/commit/${{ github.sha }}) on [${{ github.repository}}#${{ github.ref_name }}](https://github.com/${{ github.repository}}/tree/${{ github.ref_name }}) with memo `${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}`'

      - name: Discord live branch notification
        if: github.ref_name == 'v0/main'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '**SUPERADMIN LIVE** https://app.pockethost.io ([permalink](${{ steps.deployment.outputs.url }})) was updated by ${{ github.actor }} in [${{ env.GIT_COMMIT_SHORT_SHA }}](https://github.com/${{ github.repository}}/commit/${{ github.sha }}) on [${{ github.repository}}#${{ github.ref_name }}](https://github.com/${{ github.repository}}/tree/${{ github.ref_name }}): `${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}`'
